name: Deploy Dev

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

permissions:
  id-token: write
  contents: read

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::894855880155:role/github-actions-workshop-role
          aws-region: us-west-2

      - uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: infrastructure
        run: terraform init

      - name: Terraform Plan
        working-directory: infrastructure
        run: terraform plan -var="workshop_stack_base_name=workshop-dev" -var="environment=dev" -out=tfplan

      - name: Terraform Apply
        working-directory: infrastructure
        run: terraform apply -auto-approve tfplan
